(function(){
"use strict";
const root=document.getElementById("ken-page-app");if(!root)return;
const STORAGE="kps_ken_chat_v9";
let state={sessionId:`session_${Date.now()}_${Math.random().toString(36).slice(2)}`,conversation:[],serverState:{},estimate:null,leadId:null,reservation:null};
try{const s=JSON.parse(localStorage.getItem(STORAGE)||"null");if(s)state={...state,...s}}catch{}
const save=()=>localStorage.setItem(STORAGE,JSON.stringify(state));
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
root.innerHTML=`<header class="ken-chat-head"><div class="ken-mini-avatar"><div id="ken-mini-3d" class="ken-mini-3d-host" style="width:100%;height:100%"></div></div><div class="ken-chat-title"><strong>Ken</strong><span>Plumbing assistant · Estimates · Booking</span></div><div class="online-pill">Online</div></header><div class="ken-progress"><span></span></div><div class="ken-confidence-line"><span>Estimate confidence</span><strong>Tell Ken what’s happening</strong></div><div id="ken-live-estimate" class="ken-live-estimate" hidden></div><div class="ken-messages" aria-live="polite"></div><div class="ken-quick"></div><div class="ken-inputbar"><input type="text" maxlength="700" placeholder="Describe your plumbing problem…"><button class="ken-send" type="button">➜</button></div><div class="ken-footnote">The estimate adjusts as Ken learns more. More useful information generally means a narrower range; unknown details keep the range wider.</div>`;
const messages=root.querySelector(".ken-messages"),quick=root.querySelector(".ken-quick"),input=root.querySelector(".ken-inputbar input"),estimateBox=root.querySelector("#ken-live-estimate"),confidenceText=root.querySelector(".ken-confidence-line strong");
function progress(n){const v=Math.max(10,Math.min(100,Number(n)||10));root.querySelector(".ken-progress span").style.width=v+"%";confidenceText.textContent=v<35?`Low · ${v}%`:v<70?`Building · ${v}%`:v<85?`Good · ${v}%`:`High · ${v}%`}
function add(text,role="bot",persist=true){const row=document.createElement("div");row.className=`ken-row ${role}`;row.innerHTML=role==="bot"?`<div class="ken-bot-dot">K</div><div class="ken-bubble">${esc(text).replace(/\n/g,"<br>")}</div>`:`<div class="ken-bubble">${esc(text).replace(/\n/g,"<br>")}</div>`;messages.appendChild(row);messages.scrollTop=messages.scrollHeight;if(persist){state.conversation.push({role:role==="user"?"user":"assistant",content:text});state.conversation=state.conversation.slice(-30);save()}}
function html(x){const w=document.createElement("div");w.innerHTML=x;while(w.firstChild)messages.appendChild(w.firstChild);messages.scrollTop=messages.scrollHeight}
function setQuick(items=[]){quick.innerHTML="";items.forEach(t=>{const b=document.createElement("button");b.type="button";b.textContent=t;b.onclick=()=>send(t);quick.appendChild(b)})}
function typing(on){root.querySelector("[data-typing]")?.remove();if(on){const t=document.createElement("div");t.className="ken-typing";t.dataset.typing="1";t.textContent="Ken is thinking…";messages.appendChild(t);window.Ken3D?.setMood("thinking")}else window.Ken3D?.setMood("idle")}
async function api(path,opts={}){const r=await fetch(path,{...opts,headers:{"Content-Type":"application/json",...(opts.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(d.error||"Something went wrong.");e.data=d;throw e}return d}

function renderEstimate(e){
  state.estimate=e;save();progress(e.confidenceScore||30);estimateBox.hidden=false;
  estimateBox.innerHTML=`<div class="live-estimate-top"><span>LIVE ESTIMATE</span><strong>${esc(e.confidence||"Low")} confidence</strong></div><div class="live-estimate-main"><div><small>Likely job</small><b>${esc(e.jobName)}</b></div><div><small>Current range</small><b class="live-price">£${esc(e.min)}–£${esc(e.max)}</b></div></div><div class="confidence-meter"><span style="width:${Math.max(8,Math.min(100,e.confidenceScore||20))}%"></span></div><p>${e.provisional?"This is a broad working estimate. Keep chatting and Ken will narrow it where the information supports it.":"Ken has enough information for you to continue. You can still answer more questions to refine the range further."}</p>${e.canBook?'<button class="ken-action-btn" type="button" data-continue-booking>Continue to booking</button>':''}`;
  estimateBox.querySelector("[data-continue-booking]")?.addEventListener("click",showDetailsForm);
}

async function send(text){const message=String(text||"").trim();if(!message)return;add(message,"user");setQuick([]);typing(true);try{const data=await api("/api/ken",{method:"POST",body:JSON.stringify({sessionId:state.sessionId,message,history:state.conversation.slice(0,-1),state:state.serverState,page:location.pathname})});typing(false);state.sessionId=data.sessionId||state.sessionId;state.serverState=data.state||state.serverState;if(data.reply)add(data.reply,"bot");if(data.quickReplies)setQuick(data.quickReplies);if(data.estimate)renderEstimate(data.estimate);else progress(data.progress||20);save()}catch(e){typing(false);add("I’m having trouble connecting right now. Please try again in a moment, or call 020 7371 3333.","bot")}}

function showDetailsForm(){
  if(messages.querySelector("[data-customer-details]"))return;
  add("Great. I’ll take your details first, then show you the available 3-hour appointment windows.","bot");
  html(`<div class="ken-booking-card"><div class="ken-estimate-label">YOUR DETAILS</div><form class="ken-details-form" data-customer-details><input name="name" autocomplete="name" placeholder="Your name" required><input name="phone" autocomplete="tel" placeholder="Mobile number" required><textarea name="address" autocomplete="street-address" placeholder="Full address" required></textarea><input name="postcode" autocomplete="postal-code" placeholder="Postcode" required><input name="email" type="email" autocomplete="email" placeholder="Email (optional)"><button class="ken-action-btn" type="submit">Show 3-hour appointments</button></form></div>`);
  messages.querySelector("[data-customer-details]")?.addEventListener("submit",saveDetails);
}

async function saveDetails(ev){ev.preventDefault();const form=ev.currentTarget,btn=form.querySelector("button"),v=Object.fromEntries(new FormData(form).entries());btn.disabled=true;btn.textContent="Saving details…";try{const d=await api("/api/lead",{method:"POST",body:JSON.stringify({...v,sessionId:state.sessionId,estimateId:state.estimate?.estimateId})});state.leadId=d.leadId;save();form.closest(".ken-booking-card").remove();add("Thanks. Here are the next available 3-hour appointment windows.","bot");await loadSlots()}catch(e){btn.disabled=false;btn.textContent="Show 3-hour appointments";add(e.message,"bot")}}

async function loadSlots(){try{const d=await api("/api/slots");if(!d.slots?.length){add("There are no online slots showing at the moment. Please call 020 7371 3333 and we’ll arrange the quickest visit.","bot");return}html(`<div class="ken-booking-card"><div class="ken-estimate-label">AVAILABLE 3-HOUR APPOINTMENTS</div><div class="ken-slots">${d.slots.slice(0,9).map(s=>`<button type="button" class="ken-slot" data-slot="${esc(s.slotKey)}"><strong>${esc(s.dayLabel)}</strong><small>${esc(s.timeLabel)}</small></button>`).join("")}</div><p class="slot-note">Choose a slot. We’ll hold it while you complete the £75 SumUp payment.</p></div>`);messages.querySelectorAll("[data-slot]").forEach(b=>b.addEventListener("click",()=>chooseSlot(b)))}catch(e){add(e.message,"bot")}}

async function chooseSlot(btn){const all=[...messages.querySelectorAll("[data-slot]")];all.forEach(b=>b.disabled=true);btn.textContent="Holding this slot…";try{const r=await api("/api/reserve-slot",{method:"POST",body:JSON.stringify({slotKey:btn.dataset.slot,sessionId:state.sessionId,estimateId:state.estimate?.estimateId,leadId:state.leadId})});state.reservation=r.reservation;save();add(`I’ve held ${r.reservation.displayLabel} for you. I’m taking you to SumUp now to pay the £75 attendance and diagnosis fee and confirm the booking.`,"bot");const c=await api("/api/checkout",{method:"POST",body:JSON.stringify({leadId:state.leadId,estimateId:state.estimate?.estimateId,reservationId:r.reservation.reservationId})});location.href=c.checkoutUrl}catch(e){all.forEach(b=>b.disabled=false);if(e.data?.setupRequired)add("The booking flow is ready, but SumUp still needs to be connected before I can take the £75 payment.","bot");else add(e.message,"bot")}}

function boot(){if(state.conversation.length)state.conversation.forEach(m=>add(m.content,m.role==="user"?"user":"bot",false));else add("Hi, I’m Ken. Tell me what’s gone wrong in your own words. I’ll talk it through with you and keep refining the estimated price as I learn more.","bot");if(state.estimate)renderEstimate(state.estimate);setQuick(["I have a leak","My toilet has a problem","I have a tap or shower problem","I have a radiator or heating problem","I have a blocked sink or drain"]);if(!state.estimate)progress(state.serverState?.confidenceScore||15)}
document.dispatchEvent(new CustomEvent("ken-chat-ready"));root.querySelector(".ken-send").onclick=()=>{const t=input.value.trim();if(t){input.value="";send(t)}};input.addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();root.querySelector(".ken-send").click()}});document.querySelectorAll("[data-ken-prompt]").forEach(b=>b.addEventListener("click",()=>{send(b.dataset.kenPrompt);root.scrollIntoView({behavior:"smooth",block:"center"})}));boot();
})();